# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DramaCli < Formula
  desc "Drama platform CLI — manage projects, artifacts, workflows, and AI generation jobs from the command line. Single static binary, no runtime required."
  homepage "https://github.com/drama-crew/drama-platform"
  version "drama-cli-v0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.6/drama-cli_0.1.6_darwin_amd64.tar.gz"
      sha256 "09f8fc56a483acf866905842dc0a167d9c312f3a00d91dd5b4febbec2ed1380b"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.6/drama-cli_0.1.6_darwin_arm64.tar.gz"
      sha256 "0e78a06e4b79bfbd44a26366b5c1d3ed87e246f50dd926c47f33fac0ce74788d"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.6/drama-cli_0.1.6_linux_amd64.tar.gz"
      sha256 "2582522ca5261391fed383f08dd3a7c6766a0f14fe363a508d1b12168339afd2"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.6/drama-cli_0.1.6_linux_arm64.tar.gz"
      sha256 "07dcd919152c58028f8aadd9e8dbe83b9528dd9b64dd5cdcf6fa62b5c11ddf83"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  def caveats
    <<~EOS
      ffmpeg is recommended for the media and assemble command groups.
      Install it with:
        brew install ffmpeg
      Without ffmpeg those commands will exit with a clear error message;
      all other commands work without it.
    EOS
  end

  test do
    system "#{bin}/drama-cli", "--version"
  end
end
