# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DramaCli < Formula
  desc "Drama platform CLI — manage projects, artifacts, workflows, and AI generation jobs from the command line. Single static binary, no runtime required."
  homepage "https://github.com/drama-crew/drama-platform"
  version "drama-cli-v0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.3/drama-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "4cd2224a964a4abbb974c151a98a5b6c55b9e2f15db868a0941b87e7f68f6daf"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.3/drama-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "2911d07aec3b00f7d6f9fb1a658f802b09a19e9f00dfafd378d22db975141235"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.3/drama-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "7e02f76b521b559ee06a828b30b5d456dc79e9009b2583fe629c7715fb4d4190"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.1.3/drama-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "9c5bbcd2ae6cdeadd147ff3eeeb2c5ed6ed50c3557824f24d21d080a12d18f62"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  def caveats
    <<~EOS
      ffmpeg is recommended for the media and assemble command groups.
      Install it with:
        brew install ffmpeg
      Without ffmpeg those commands will exit with a clear error message;
      all other commands work without it.
    EOS
  end

  test do
    system "#{bin}/drama-cli", "--version"
  end
end
