# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DramaCli < Formula
  desc "Drama platform CLI — manage projects, artifacts, workflows, and AI generation jobs from the command line. Single static binary, no runtime required."
  homepage "https://github.com/drama-crew/drama-platform"
  version "drama-cli-v0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.3.0/drama-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "0f648cab9eb1183c419f8a8c9a6561f86dbb1ac2879c34dc5f2a1eaea3566e2e"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.3.0/drama-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "cda9bd3ec2e6fb9c3caac443081b02e1a15c48a257dceda039dc53898a1b6395"

      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.3.0/drama-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "defd5b6173e5c45ff2ae3060cc699a1bd4fcbbed55c882893ec0bcc835c6c2b4"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drama-crew/drama-cli/releases/download/drama-cli-v0.3.0/drama-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "7f811340e6ef57bf7ae6c5078538e85bb9a333e170ce35f6fe53e3058295922e"
      define_method(:install) do
        bin.install "drama-cli"
      end
    end
  end

  def caveats
    <<~EOS
      ffmpeg is recommended for the media and assemble command groups.
      Install it with:
        brew install ffmpeg
      Without ffmpeg those commands will exit with a clear error message;
      all other commands work without it.
    EOS
  end

  test do
    system "#{bin}/drama-cli", "--version"
  end
end
